<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Security') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="custom-div">
                        <h3 class="text-xl">Google 2FA Authentication - VERY IMPORTANT</h3>
                        <h6 class="text-lg font-medium">We use Google 2FA authentication to add an extra layer of
                            security to your account.
                            Next time you will log in, you will be asked to enter a 6-digit code generated by the Google
                            Authenticator app on your phone.</h6>
                        <h6 class="text-lg font-medium">We recommend using the Authy app as your authenticator. Authy
                            provides a convenient and secure way to manage your OTP codes for multiple accounts. And its
                            easy to set up it. Below You can find Your OTP secret</h6>
                        <h6 class="text-lg font-medium">You can download the Authy app from the following app
                            stores:</h6>
                        <div class="flex flex-col space-x-4 mb-10">
                            <a href="https://play.google.com/store/apps/details?id=com.authy.authy" target="_blank"
                               rel="noopener" class="flex p-2 bg-gray-800 rounded-e-2xl mt-3">Google Play Store</a>
                            <a href="https://apps.apple.com/us/app/authy/id494168017" target="_blank" rel="noopener"
                               class="flex p-2 bg-gray-800 rounded-e-2xl mt-3">App Store</a>
                        </div>
                    </div>
                    <br>
                    <br>
                    <form>
                        <div class="custom-div">
                            <div class="text-lg">
                                <label for="otp_secret" class="text-lg font-bold text-red-500">Your OTP Secret:</label>
                                <x-input type="password" value="{{auth()->user()->otp_secret}}" id="otp_secret"
                                         name="otp_secret" readonly="readonly" class="mt-3"/>
                                <x-button type="button" onclick="togglePasswordVisibility()" class="ml-3">
                                    Show/Hide
                                </x-button>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        function togglePasswordVisibility() {
            var passwordInput = document.getElementById("otp_secret");
            if (passwordInput.type === "password") {
                passwordInput.type = "text";
            } else {
                passwordInput.type = "password";
            }
        }
    </script>
</x-app-layout>
